name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: iffy/install-nim@v1
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get -y install libdbus-1-dev gnome-keyring
    - name: Build
      run: nimble build -y
    - name: Test
      if: runner.os != 'Linux'
      run: nimble test -y
    - name: Linux Test
      if: runner.os == 'Linux'
      run: dbus-run-session -- bash -c 'echo "" | gnome-keyring-daemon --unlock && nimble test'
